const $=id=>document.getElementById(id);
const token=location.hash.slice(1);let cursor='',state,group='running',selectedOutput='',stopped=false;
const expanded=new Set(),initialized=new Set();const terminal=new Set(['execution_completed','failed','cancelled','skipped']);
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=String(text);return node;};
const fmt=n=>n===undefined?'—':new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
const label=s=>({execution_completed:'Executed · unreviewed',running:'Running',queued:'Queued',failed:'Failed',cancelled:'Stopped',skipped:'Skipped',incomplete:'Incomplete'})[s]??s;
const duration=n=>n===undefined?'—':n<60?`${n.toFixed(1)}s`:`${Math.floor(n/60)}m ${Math.floor(n%60)}s`;
if(new URLSearchParams(location.search).has('popout')){document.body.classList.add('popout');$('popout').hidden=true;}
async function api(path){const r=await fetch(path,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw new Error(`Observer unavailable (${r.status})`);return r;}
async function openOutput(task){selectedOutput=task.id;$('output-title').textContent=task.title;$('output-text').textContent='Loading recorded output…';$('output-dialog').showModal();try{const r=await api('/api/output?task='+encodeURIComponent(task.id));if(selectedOutput===task.id)$('output-text').textContent=await r.text();}catch(e){$('output-text').textContent=e.message;}}
function render(){if(!state)return;const focusKey=document.activeElement?.dataset?.focusKey;const p=state,s=p.stats;$('run-name').textContent=p.name;$('title').textContent=p.name;
 $('summary').replaceChildren(el('span','status-badge '+p.status,label(p.status)),el('p','summary-text',p.tasks.length+' tasks · '+fmt(s.observedTokens)+' observed tokens'));
 $('running-count').textContent=p.tasks.filter(t=>!terminal.has(t.state)).length;$('finished-count').textContent=s.finished;
 $('running-tab').setAttribute('aria-selected',String(group==='running'));$('finished-tab').setAttribute('aria-selected',String(group==='finished'));
 const phases=$('phases');phases.replaceChildren();for(const phase of p.phases){const tasks=phase.tasks.filter(t=>group==='running'?!terminal.has(t.state):terminal.has(t.state));if(!tasks.length)continue;
 const key=group+':'+phase.id;if(!initialized.has(key)){initialized.add(key);expanded.add(key);}const section=el('section','phase');const button=el('button','phase-toggle');button.setAttribute('aria-expanded',String(expanded.has(key)));button.append(el('span','chevron',expanded.has(key)?'⌄':'›'),el('span','phase-name',phase.title),el('span','phase-count',tasks.length));button.onclick=()=>{expanded.has(key)?expanded.delete(key):expanded.add(key);render();const next=[...document.querySelectorAll('.phase-toggle')].find(b=>b.dataset.phase===key);next?.focus();};button.dataset.phase=key;button.dataset.focusKey='phase:'+key;section.append(button);
 if(expanded.has(key)){const list=el('div','task-list');for(const task of tasks){const row=el('div','task');row.append(el('span','state-dot '+task.state));const body=el('div','task-body');body.append(el('strong','task-title',task.title),el('div','task-meta',`${task.role} · ${label(task.state)}`),el('div','task-model',task.model?`${task.model} · ${task.modelSource}`:'Effective model unknown'),el('div','task-usage',`${fmt(task.tokens)} tokens  ·  ${duration(task.seconds)}`));if(task.error)body.append(el('p','task-error',task.error));if(task.outputAvailable){const output=el('button','text-button','Open recorded output');output.dataset.focusKey='output:'+task.id;output.onclick=()=>openOutput(task);body.append(output);}row.append(body);list.append(row);}section.append(list);}phases.append(section);}
 if(!phases.children.length)phases.append(el('p','empty',group==='running'?'No active tasks in this snapshot.':'No finished tasks yet.'));
 const stats=$('stats');stats.replaceChildren();for(const [name,value] of [['Avg generation tok/s',s.avgTps?.toFixed(1)??'—'],['Estimated response tok/s',s.estimatedTps?.toFixed(1)??'—'],['Measured samples',`${s.measured}/${s.samples}`],['Exactly one review','—'],['Unreviewed',s.unreviewed],['Failed / stopped',`${s.failed} / ${s.cancelled}`]]){const row=el('div','metric');row.append(el('span','',name),el('strong','',value));stats.append(row);}
 const evidence=$('evidence');evidence.replaceChildren();for(const warning of p.warnings)evidence.append(el('p','',warning));evidence.append(el('p','','Legacy model names are configured identities. Response timing includes network and reasoning; generation timing is not inferred.'),el('p','digest','Snapshot '+p.sourceDigest.slice(0,16)));
 const models=[...new Set(p.tasks.filter(t=>t.state==='running'&&t.model).map(t=>t.model))];const footerModels=models.length?models[0]+(models.length>1?` +${models.length-1}`:'')+' (configured)':'—';$('footer').textContent=`Workspace | avg ${s.avgTps?.toFixed(1)??'—'} tok/s | ${footerModels} | ${s.running} running`;
 const messages=$('messages');messages.replaceChildren();const intro=el('article','message');intro.append(el('span','message-author','WORKFLOW'),el('p','',`${p.name} · ${label(p.status)}`),el('p','muted',`Started ${new Date(p.startedAt).toLocaleString()}. Select a recorded output to inspect the work.`));messages.append(intro);
 for(const task of p.tasks.filter(t=>t.outputAvailable)){const message=el('article','message');message.append(el('span','message-author',task.role.toUpperCase()),el('h3','',task.title),el('p','muted',label(task.state)));const button=el('button','outline-button','Read task output →');button.dataset.focusKey='message:'+task.id;button.onclick=()=>openOutput(task);message.append(button);messages.append(message);}
 if(focusKey&&!$('output-dialog').open){const target=[...document.querySelectorAll('[data-focus-key]')].find(n=>n.dataset.focusKey===focusKey);(target??$(group+'-tab')).focus();}
}
$('running-tab').onclick=()=>{group='running';render();};$('finished-tab').onclick=()=>{group='finished';render();};
for(const id of ['running-tab','finished-tab'])$(id).onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();group=group==='running'?'finished':'running';render();$(group+'-tab').focus();}};
$('close-output').onclick=()=>{$('output-dialog').close();selectedOutput='';};$('popout').onclick=()=>{const win=window.open('/?popout=1#'+token,'titan-workflow-'+(state?.runId??''),'popup,width=480,height=820');if(!win)$('connection').textContent='Popout blocked — allow popups for this page';};
$('workflow-nav').onclick=()=>{$('workflow').scrollIntoView({behavior:'smooth'});$('running-tab').focus();};$('chat-nav').onclick=()=>$('chat').scrollIntoView({behavior:'smooth'});
async function poll(){if(stopped)return;try{const r=await api('/api/snapshot?after='+encodeURIComponent(cursor));const frame=await r.json();if(frame.kind==='snapshot'&&frame.cursor!==cursor){state=frame.projection;cursor=frame.cursor;render();}$('connection').textContent='● Connected';$('connection').className='connected';}catch(e){$('connection').textContent='Disconnected · retrying';$('connection').className='disconnected';}finally{if(!stopped)setTimeout(poll,1000);}}
window.addEventListener('pagehide',()=>{stopped=true;});poll();
